spring:
  application:
    name: docuchat

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /api/v1
